_comment: 模型推理配置（YOLO / 分类模型）

yolo_model_configs:
  - name: yolo26_ensemble
    input_name: raw_image
    input_size: 640
    conf_thresh: 0.5
    iou_thresh: 0.45
    label_map_file: config/names/coco.names
  - name: yolov5_ensemble
    input_name: raw_image
    input_size: 640
    conf_thresh: 0.5
    iou_thresh: 0.45
    label_map_file: config/names/yolov5_foreign_objects.names

classification_configs:
  - name: resnet_smoke
    model_name: classifier_ensemble
    input_name: raw_image
    output_name: output
    labels: [smoking, normal]
    conf_thresh: 0.5
    target_class: smoking
    expand_ratio: 2.0
